#!/bin/bash

set -e

# Parse image name
tagStart=$(expr index "${IMAGE_NAME}" :)
#repoName=${IMAGE_NAME:0:tagStart-1}

echo "Post-push processing image: ${IMAGE_NAME}. Tag: ${IMAGE_NAME:tagStart}" ## For some reason ${CACHE_TAG} is not available
echo "Current commit=${SOURCE_COMMIT}"
echo "Current branch=${SOURCE_BRANCH}"

#Additional compound version+SHA tag
if [[ "${IMAGE_NAME:tagStart}" =~ ^v?([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+)$ ]]; then \
  CTAG="${IMAGE_NAME:tagStart}_${SOURCE_COMMIT##*/}"
  echo "Additional compound tag: ${CTAG}"
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${CTAG}
  docker push ${DOCKER_REPO}:${CTAG}
fi

#SHA hash tag for any build
for tag in ${SOURCE_COMMIT} $(git tag -l --points-at HEAD | sed 's/^v//' || echo ""); do
  echo "Additional tag: ${tag##*/}"
  docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${tag##*/}
  docker push ${DOCKER_REPO}:${tag##*/}
  if [[ "${tag}" =~ ^v?([0-9]+\.)?([0-9]+\.)?(\*|[0-9]+)$ ]]; then \
    CTAG="${tag}_${SOURCE_COMMIT##*/}"
    echo "Additional compound tag: ${CTAG}"
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${CTAG}
    docker push ${DOCKER_REPO}:${CTAG} | tee push.log
    DIGEST=$(grep -oE '(digest: )(sha256):([A-Fa-f0-9]+)' push.log | cut -d':' -f3)
    echo "Additional compound tag with sha256 digest hex: ${CTAG}_${DIGEST}"
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${CTAG}_${DIGEST}
    docker push ${DOCKER_REPO}:${CTAG}_${DIGEST}
  fi
done